# This is a basic workflow to help you get started with Actions

name: Deploy-Infrastructure

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: 'dev-personal-cv-website-frontend'

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout Repo'
              uses: actions/checkout@v3

            - name: 'Azure CLI Login via OIDC'
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: 'Deploy Storage Account'
              run: |
                az deployment group create --resource-group ${{ env.RESOURCE_GROUP }} --name deploy-website-infra --template-file ./bicep-scripts/storageAccount.bicep --parameters ./bicep-scripts/parameters/storageAccount.bicepparam
                storageAccName=$(az deployment group show -g ${{ env.RESOURCE_GROUP }} -n deploy-website-infra --query properties.outputs.storageAccountName.value | tr -d \")
                echo "STORAGE_ACCOUNT_NAME=$storageAccName" >> $GITHUB_ENV